# Generated by Django 5.2.14 on 2026-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanprofile',
            name='nmap_version_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='openvas_config',
            field=models.CharField(choices=[('base', 'Base'), ('discovery', 'Discovery'), ('full_and_fast', 'Full and fast')], default='base', max_length=20),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='use_openvas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scanprofile',
            name='target_ip',
            field=models.CharField(max_length=255),
        ),
    ]
