# Generated by Django 5.2.14 on 2026-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_scanprofile_nmap_version_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanprofile',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='schedule',
            field=models.CharField(choices=[('none', 'Nėra'), ('hourly', 'Kas valandą'), ('daily', 'Kas dieną'), ('weekly', 'Kas savaitę')], default='none', max_length=20),
        ),
    ]
