# Generated by Django 5.2.14 on 2026-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0003_scanprofile_next_run_at_scanprofile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanprofile',
            name='schedule_time',
            field=models.CharField(default='08:00', max_length=5),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='schedule_weekday',
            field=models.IntegerField(default=0),
        ),
    ]
